#!/bin/bash
awk '
/<\/div>$/ && !done {
  print "      {/* Customer View Modal */}"
  print "      {viewingCustomer && ("
  print "        <div className=\"fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4\">"
  print "          <Card className=\"w-full max-w-5xl max-h-[90vh] overflow-y-auto border-none shadow-2xl animate-in zoom-in-95 duration-200\">"
  print "            <CardHeader className=\"border-b border-slate-100 pb-4 sticky top-0 bg-white z-10 flex flex-row items-center justify-between\">"
  print "              <div>"
  print "                <CardTitle className=\"text-2xl font-black text-slate-800 flex items-center gap-2\">"
  print "                  <Briefcase size={24} className=\"text-indigo-600\" />"
  print "                  ملف العميل: {viewingCustomer.name}"
  print "                </CardTitle>"
  print "                <CardDescription className=\"font-bold mt-1 text-slate-500\">{viewingCustomer.type} - {viewingCustomer.phone}</CardDescription>"
  print "              </div>"
  print "              <Button variant=\"ghost\" onClick={() => setViewingCustomer(null)} className=\"font-bold text-slate-500 hover:text-slate-800\">"
  print "                إغلاق"
  print "              </Button>"
  print "            </CardHeader>"
  print "            <CardContent className=\"pt-6 space-y-8\">"
  print "              {/* Stats */}"
  print "              <div className=\"grid grid-cols-1 md:grid-cols-3 gap-4\">"
  print "                <div className=\"bg-slate-50 p-4 rounded-2xl border border-slate-100\">"
  print "                  <p className=\"text-xs font-black text-slate-500 uppercase tracking-widest mb-1\">الرصيد المالي الحالي</p>"
  print "                  <div className={`text-2xl font-black ${viewingCustomer.balance > 0 ? \047text-red-600\047 : viewingCustomer.balance < 0 ? \047text-emerald-600\047 : \047text-slate-700\047}`}>"
  print "                    {Math.abs(viewingCustomer.balance).toLocaleString(\047ar-EG\047)} ج.م"
  print "                  </div>"
  print "                  <p className=\"text-xs font-bold text-slate-400 mt-1\">{viewingCustomer.balance > 0 ? \047عليه (مدين)\047 : viewingCustomer.balance < 0 ? \047له (دائن)\047 : \047مُصفى\047}</p>"
  print "                </div>"
  print "                <div className=\"bg-slate-50 p-4 rounded-2xl border border-slate-100\">"
  print "                  <p className=\"text-xs font-black text-slate-500 uppercase tracking-widest mb-1\">عدد الطلبيات (أوامر البيع)</p>"
  print "                  <div className=\"text-2xl font-black text-slate-800\">"
  print "                    {salesOrders.filter(o => o.customerName === viewingCustomer.name).length}"
  print "                  </div>"
  print "                </div>"
  print "                <div className=\"bg-slate-50 p-4 rounded-2xl border border-slate-100\">"
  print "                  <p className=\"text-xs font-black text-slate-500 uppercase tracking-widest mb-1\">إجمالي المدفوعات (المحصلة)</p>"
  print "                  <div className=\"text-2xl font-black text-slate-800\">"
  print "                    {customerPayments.filter(p => p.customerId === viewingCustomer.id).reduce((sum, p) => sum + p.amount, 0).toLocaleString(\047ar-EG\047)} ج.م"
  print "                  </div>"
  print "                </div>"
  print "              </div>"
  print "              "
  print "              {/* Tabs / Sections */}"
  print "              <div className=\"space-y-6\">"
  print "                <div>"
  print "                  <h3 className=\"text-lg font-black text-slate-800 flex items-center gap-2 mb-4 border-b border-slate-100 pb-2\">"
  print "                    <FileText size={18} className=\"text-indigo-600\" />"
  print "                    الطلبيات وأوامر البيع المرتبطة"
  print "                  </h3>"
  print "                  <div className=\"bg-white border border-slate-200 rounded-xl overflow-hidden\">"
  print "                    <Table>"
  print "                      <TableHeader className=\"bg-slate-50\">"
  print "                        <TableRow>"
  print "                          <TableHead className=\"font-black text-slate-600\">التاريخ</TableHead>"
  print "                          <TableHead className=\"font-black text-slate-600\">إجمالي البيع</TableHead>"
  print "                          <TableHead className=\"font-black text-slate-600\">التكلفة المتوقعة</TableHead>"
  print "                          <TableHead className=\"font-black text-slate-600\">الربحية المتوقعة</TableHead>"
  print "                        </TableRow>"
  print "                      </TableHeader>"
  print "                      <TableBody>"
  print "                        {salesOrders.filter(o => o.customerName === viewingCustomer.name).length === 0 ? ("
  print "                          <TableRow><TableCell colSpan={4} className=\"text-center text-slate-400 font-bold py-6\">لا توجد طلبيات</TableCell></TableRow>"
  print "                        ) : ("
  print "                          salesOrders.filter(o => o.customerName === viewingCustomer.name).map(order => {"
  print "                            const totalSelling = order.items.reduce((s, i) => s + (i.sellingPrice || 0), 0);"
  print "                            const totalCost = order.items.reduce((s, i) => s + (i.cogs || 0) + (i.logisticsCost || 0), 0);"
  print "                            return ("
  print "                              <TableRow key={order.id}>"
  print "                                <TableCell className=\"font-bold\">{order.date}</TableCell>"
  print "                                <TableCell className=\"font-black text-slate-700\">{totalSelling.toLocaleString(\047ar-EG\047)} ج.م</TableCell>"
  print "                                <TableCell className=\"font-bold text-slate-500\">{totalCost.toLocaleString(\047ar-EG\047)} ج.م</TableCell>"
  print "                                <TableCell className=\"font-black text-emerald-600\">{(totalSelling - totalCost).toLocaleString(\047ar-EG\047)} ج.م</TableCell>"
  print "                              </TableRow>"
  print "                            )"
  print "                          })"
  print "                        )}"
  print "                      </TableBody>"
  print "                    </Table>"
  print "                  </div>"
  print "                </div>"
  print "                <div>"
  print "                  <h3 className=\"text-lg font-black text-slate-800 flex items-center gap-2 mb-4 border-b border-slate-100 pb-2\">"
  print "                    <CreditCard size={18} className=\"text-emerald-600\" />"
  print "                    سجل الدفعات والمقبوضات"
  print "                  </h3>"
  print "                  <div className=\"bg-white border border-slate-200 rounded-xl overflow-hidden\">"
  print "                    <Table>"
  print "                      <TableHeader className=\"bg-slate-50\">"
  print "                        <TableRow>"
  print "                          <TableHead className=\"font-black text-slate-600\">التاريخ</TableHead>"
  print "                          <TableHead className=\"font-black text-slate-600\">المبلغ</TableHead>"
  print "                          <TableHead className=\"font-black text-slate-600\">طريقة الدفع</TableHead>"
  print "                          <TableHead className=\"font-black text-slate-600\">ملاحظات</TableHead>"
  print "                        </TableRow>"
  print "                      </TableHeader>"
  print "                      <TableBody>"
  print "                        {customerPayments.filter(p => p.customerId === viewingCustomer.id).length === 0 ? ("
  print "                          <TableRow><TableCell colSpan={4} className=\"text-center text-slate-400 font-bold py-6\">لا توجد مدفوعات</TableCell></TableRow>"
  print "                        ) : ("
  print "                          customerPayments.filter(p => p.customerId === viewingCustomer.id).map(payment => ("
  print "                            <TableRow key={payment.id}>"
  print "                              <TableCell className=\"font-bold\">{payment.date}</TableCell>"
  print "                              <TableCell className=\"font-black text-emerald-600\">{payment.amount.toLocaleString(\047ar-EG\047)} ج.م</TableCell>"
  print "                              <TableCell className=\"font-bold text-slate-600\">{payment.paymentMethod} {payment.referenceNumber ? `(${payment.referenceNumber})` : \047\047}</TableCell>"
  print "                              <TableCell className=\"text-slate-500 font-medium\">{payment.notes}</TableCell>"
  print "                            </TableRow>"
  print "                          ))"
  print "                        )}"
  print "                      </TableBody>"
  print "                    </Table>"
  print "                  </div>"
  print "                </div>"
  print "              </div>"
  print "            </CardContent>"
  print "          </Card>"
  print "        </div>"
  print "      )}"
  print "    </div>"
  print "  );"
  done = 1
  next
}
{ print $0 }
' src/components/CustomersManager.tsx > src/components/CustomersManager.tsx.tmp && mv src/components/CustomersManager.tsx.tmp src/components/CustomersManager.tsx
